require "user.keymaps"
require "user.packer"
require "user.impatient"
require "user.autocommands"
require "user.colorscheme"
require "user.notify"
require "user.whichkey"
require "user.cmp"
-- require "user.navic"
-- require "user.lsp-inlayhints"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.gitsigns"
require "user.diffview"
require "user.nvim-tree"
require "user.lualine"
require "user.toggleterm"
require "user.alpha"
require "user.leap"
require "user.numb"
require "user.dial"
require "user.colorizer"
require "user.spectre"
require "user.todo-comments"
require "user.harpoon"
require "user.symbol-outline"
require "user.ts-context"
require "user.illuminate"
require "user.lir"
require "user.options"
require "user.nvim-webdev-icons"
require "user.dressing"
require "user.goto-preview"
-- require "user.fidget"
require "user.true-zen"
require "user.dap"
require "user.mind"
require("user.winbar").create_winbar()
-- NOTE: Doesn't work with vertical/horizontal toggleterm 😐
require "user.windows"
require "user.smooth-cursor"
-- require "user.tint"
require "user.zippy"
-- require "user.delaytrain"
