require "user.keymaps"
require "user.options"
require "user.autocommands"
require "user.lazy"
require "user.colorscheme"
require "user.autopairs"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.comment"
require "user.gitsigns"
require "user.toggleterm"
require "user.colorizer"
require "user.spectre"
require "user.todo-comments"
require "user.grapple"
-- require "user.dressing"
require "user.dap"
require "user.zen-mode"
-- require "user.statusline"
