local Remap = require "user.keymaps.bind"
local nnoremap = Remap.nnoremap

nnoremap("<leader><leader>dR", "<cmd>lua require'dap'.run_to_cursor()<cr>")
nnoremap("<leader><leader>dE", "<cmd>lua require'dapui'.eval(vim.fn.input '[Expression] > ')<cr>")
nnoremap("<leader><leader>dC", "<cmd>lua require'dap'.set_breakpoint(vim.fn.input '[Condition] > ')<cr>")
nnoremap("<leader><leader>dU", "<cmd>lua require'dapui'.toggle()<cr>")
nnoremap("<leader><leader>db", "<cmd>lua require'dap'.step_back()<cr>")
nnoremap("<leader><leader>dc", "<cmd>lua require'dap'.continue()<cr>")
nnoremap("<leader><leader>dd", "<cmd>lua require'dap'.disconnect()<cr>")
nnoremap("<leader><leader>de", "<cmd>lua require'dapui'.eval()<cr>")
nnoremap("<leader><leader>dg", "<cmd>lua require'dap'.session()<cr>")
nnoremap("<leader><leader>dh", "<cmd>lua require'dap.ui.widgets'.hover()<cr>")
nnoremap("<leader><leader>dS", "<cmd>lua require'dap.ui.widgets'.scopes()<cr>")
nnoremap("<leader><leader>di", "<cmd>lua require'dap'.step_into()<cr>")
nnoremap("<leader><leader>do", "<cmd>lua require'dap'.step_over()<cr>")
nnoremap("<leader><leader>dp", "<cmd>lua require'dap'.pause.toggle()<cr>")
nnoremap("<leader><leader>dq", "<cmd>lua require'dap'.close()<cr>")
nnoremap("<leader><leader>dr", "<cmd>lua require'dap'.repl.toggle()<cr>")
nnoremap("<leader><leader>ds", "<cmd>lua require'dap'.continue()<cr>")
nnoremap("<leader><leader>dt", "<cmd>lua require'dap'.toggle_breakpoint()<cr>")
nnoremap("<leader><leader>dx", "<cmd>lua require'dap'.terminate()<cr>")
nnoremap("<leader><leader>du", "<cmd>lua require'dap'.step_out()<cr>")
