require("blink.cmp").setup {
  keymap = {
    preset = "default",
    ["<C-n>"] = { "show", "select_next", "fallback" },
    ["<C-p>"] = { "show", "select_prev", "fallback" },
    ["<C-c>"] = { "hide", "fallback" },
    ["<C-u>"] = { "scroll_documentation_up", "fallback" },
    ["<C-d>"] = { "scroll_documentation_down", "fallback" },
    ["<C-l>"] = { "snippet_forward", "fallback" },
    ["<C-h>"] = { "snippet_backward", "fallback" },
  },
  appearance = {
    kind_icons = {
      Text = "t",
      Method = "m",
      Function = "f",
      Constructor = "c",
      Field = ".",
      Variable = "v",
      Property = "p",
      Class = "C",
      Interface = "I",
      Struct = "S",
      Module = "M",
      Unit = "u",
      Value = "V",
      Enum = "E",
      EnumMember = "e",
      Keyword = "k",
      Snippet = "s",
      Color = "#",
      File = "F",
      Reference = "&",
      Folder = "/",
      Constant = "K",
      Event = "!",
      Operator = "+",
      TypeParameter = "T",
    },
  },
  completion = {
    menu = {
      auto_show = false,
      border = "rounded",
      winhighlight = "Normal:Normal,FloatBorder:FloatBorder,CursorLine:PmenuSel,Search:None",
    },
    documentation = {
      auto_show = true,
      auto_show_delay_ms = 200,
      window = {
        border = "rounded",
        winhighlight = "Normal:Normal,FloatBorder:FloatBorder,Search:None",
      },
    },
    list = {
      selection = { preselect = false, auto_insert = false },
    },
    ghost_text = { enabled = false },
  },
  sources = {
    default = { "lsp", "buffer", "path" },
  },
  signature = {
    enabled = true,
    window = {
      border = "rounded",
      winhighlight = "Normal:Normal,FloatBorder:FloatBorder,Search:None",
    },
  },
}
