local statusline = require "user.statusline"
local options = {
  backup = false,
  clipboard = "unnamedplus",
  cmdheight = 1,
  completeopt = { "menuone", "noselect", "fuzzy", "popup" },
  complete = ".,w,b,u,t,o",
  conceallevel = 0,
  fileencoding = "utf-8",
  hlsearch = true,
  ignorecase = true,
  showtabline = 1,
  smartcase = true,
  smartindent = true,
  autoindent = true,
  splitbelow = true,
  splitright = true,
  swapfile = false,
  termguicolors = true,
  timeoutlen = 500,
  undofile = true,
  updatetime = 1000,
  writebackup = false,
  expandtab = true,
  shiftwidth = 2,
  tabstop = 2,
  cursorline = true,
  number = true,
  relativenumber = true,
  statusline = statusline.full,
  laststatus = 2,
  signcolumn = "yes",
  wrap = false,
  scrolloff = 8,
  sidescrolloff = 8,
  listchars = "tab:→ ,trail:·,lead:·,extends:…,precedes:…,eol:↵",
  list = false,
  foldmethod = "marker",
  -- <C-n> as autocomplete menu trigger instead of <Tab>; wildchar wants a number
  wildchar = 14,
  winborder = "rounded",
}

for k, v in pairs(options) do
  vim.opt[k] = v
end
